## Multiple Linear Regression

**Business -> Build a model that can predict accurate profits on basis of RND and MKT**

## Step1: Data Ingestion/Data Gathering

In [1]:
import pandas as pd
path = r"E:\DATA SCIENTIST\Analysis\pandas\datasets\50_Startups.csv"
df = pd.read_csv(path)
df.head()

,RND,ADMIN,MKT,STATE,PROFIT
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94


## Step2: Perform basic data quality checks

In [2]:
df.shape

(50, 5)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RND     50 non-null     float64
 1   ADMIN   50 non-null     float64
 2   MKT     50 non-null     float64
 3   STATE   50 non-null     object 
 4   PROFIT  50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
df.isna().sum()

RND       0
ADMIN     0
MKT       0
STATE     0
PROFIT    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

## Step3: Separate the X and Y features

    X: RND , MKT
    Y: PROFIT

In [6]:
X = df[['RND','MKT']]
Y = df[['PROFIT']]
display(X)
display(Y)

,RND,MKT
0,165349.20,471784.10
1,162597.70,443898.53
2,153441.51,407934.54
3,144372.41,383199.62
4,142107.34,366168.42
5,131876.90,362861.36
6,134615.46,127716.82
7,130298.13,323876.68
8,120542.52,311613.29
9,123334.88,304981.62


,PROFIT
0,192261.83
1,191792.06
2,191050.39
3,182901.99
4,166187.94
5,156991.12
6,156122.51
7,155752.60
8,152211.77
9,149759.96


### Step4: Feature Engineering:-> Data Cleaning

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

num_pipe = make_pipeline(SimpleImputer(strategy='median')).set_output(transform='pandas')
num_pipe

,steps,"[('simpleimputer', ...)]"
,transform_input,None
,memory,None
,verbose,False
,missing_values,nan
,strategy,'median'
,fill_value,None
,copy,True
,add_indicator,False
,keep_empty_features,False


### Step5: Separate our data into training and testing

dataset size is small: 80% and above training : 20% and below testing

In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.8,random_state=21)


In [11]:
print("X Training and Testing size :" , xtrain.shape,xtest.shape)

X Training and Testing size : (40, 2) (10, 2)


In [12]:
print("Y Training and Testing size :" , ytrain.shape,ytest.shape)

Y Training and Testing size : (40, 1) (10, 1)


### Apply the pipeline on training and testing data

In [13]:
num_pipe.fit(xtrain)

,steps,"[('simpleimputer', ...)]"
,transform_input,None
,memory,None
,verbose,False
,missing_values,nan
,strategy,'median'
,fill_value,None
,copy,True
,add_indicator,False
,keep_empty_features,False


In [14]:
xtrain_pre = num_pipe.transform(xtrain)
xtest_pre = num_pipe.transform(xtest)

### Step5: Model Building

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain_pre,xtrain)


,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


### Check for coefficients(slopes) and yintercept

In [16]:
X.shape[1]

2

In [17]:
X.columns

Index(['RND', 'MKT'], dtype='object')

In [18]:
model.coef_

array([[1.00000000e+00, 4.09488250e-17],
       [1.06570565e-15, 1.00000000e+00]])

In [19]:
model.intercept_

array([-1.45519152e-11, -1.45519152e-10])

### PROFIT_PREDICTED = 46739.04 + (0.806)RND + (0.028)MKT

In [20]:
ypred_test = model.predict(xtest_pre)
ypred_test[:5]

array([[130298.13, 323876.68],
       [ 22177.74,  28334.72],
       [ 15505.73,  35534.17],
       [ 64664.71, 137962.62],
       [119943.24, 256512.92]])

In [21]:
ytest.head()

,PROFIT
7,155752.60
44,65200.33
43,69758.98
25,107404.34
14,132602.65


### Step 6: Model Evaluation : Performance Metrics

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression  # example model
import numpy as np

# Example dataset (replace with your own X, y)
# X = ...
# y = ...

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on test set only
ypred_test = model.predict(X_test)

# Ensure arrays are 1-D
y_test = np.ravel(y_test)
ypred_test = np.ravel(ypred_test)

# Metrics
mse = mean_squared_error(y_test, ypred_test)
mae = mean_absolute_error(y_test, ypred_test)
rmse = mse**0.5
r2 = r2_score(y_test, ypred_test)

print("Testing scores")
print(f"MSE: {mse}")
print(f"MAE: {mae}")
print(f"RMSE: {rmse}")
print(f"R2 score - Coefficient of Determination: {r2*100:.2f}")


Testing scores
MSE: 67343832.58979604
MAE: 6469.181721468585
RMSE: 8206.32881316585
R2 score - Coefficient of Determination: 91.68


### R2 Score for the model is above 80%. We can consider this model for final deployments.

In [27]:
import joblib
joblib.dump(model,"MLR_ProfitPrediction.joblib")
joblib.dump(num_pipe,"cleaning_pipeline.joblib")

['cleaning_pipeline.joblib']

In [28]:
model_loaded= joblib.load("MLR_ProfitPrediction.joblib")
pipeline_loaded = joblib.load("cleaning_pipeline.joblib")

In [29]:
model_loaded

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [30]:
pipeline_loaded

,steps,"[('simpleimputer', ...)]"
,transform_input,None
,memory,None
,verbose,False
,missing_values,nan
,strategy,'median'
,fill_value,None
,copy,True
,add_indicator,False
,keep_empty_features,False
